package beans;
// Generated 12 juil. 2016 14:22:32 by Hibernate Tools 4.3.1


import java.math.BigDecimal;
import java.util.Date;
import java.util.HashSet;
import java.util.Set;

/**
 * Circuit generated by hbm2java
 */
public class Circuit  implements java.io.Serializable {


     private long id;
     private String descriptif;
     private String villeDepart;
     private String paysDepart;
     private String villeArrivee;
     private String paysArrivee;
     private Date dateDepart;
     private Long placesDispo;
     private BigDecimal duree;
     private Long prix;
     private Set etapes = new HashSet(0);
     private Set reservations = new HashSet(0);

    public Circuit() {
    }

	
    public Circuit(long id) {
        this.id = id;
    }
    public Circuit(long id, String descriptif, String villeDepart, String paysDepart, String villeArrivee, String paysArrivee, Date dateDepart, Long placesDispo, BigDecimal duree, Long prix, Set etapes, Set reservations) {
       this.id = id;
       this.descriptif = descriptif;
       this.villeDepart = villeDepart;
       this.paysDepart = paysDepart;
       this.villeArrivee = villeArrivee;
       this.paysArrivee = paysArrivee;
       this.dateDepart = dateDepart;
       this.placesDispo = placesDispo;
       this.duree = duree;
       this.prix = prix;
       this.etapes = etapes;
       this.reservations = reservations;
    }
   
    public long getId() {
        return this.id;
    }
    
    public void setId(long id) {
        this.id = id;
    }
    public String getDescriptif() {
        return this.descriptif;
    }
    
    public void setDescriptif(String descriptif) {
        this.descriptif = descriptif;
    }
    public String getVilleDepart() {
        return this.villeDepart;
    }
    
    public void setVilleDepart(String villeDepart) {
        this.villeDepart = villeDepart;
    }
    public String getPaysDepart() {
        return this.paysDepart;
    }
    
    public void setPaysDepart(String paysDepart) {
        this.paysDepart = paysDepart;
    }
    public String getVilleArrivee() {
        return this.villeArrivee;
    }
    
    public void setVilleArrivee(String villeArrivee) {
        this.villeArrivee = villeArrivee;
    }
    public String getPaysArrivee() {
        return this.paysArrivee;
    }
    
    public void setPaysArrivee(String paysArrivee) {
        this.paysArrivee = paysArrivee;
    }
    public Date getDateDepart() {
        return this.dateDepart;
    }
    
    public void setDateDepart(Date dateDepart) {
        this.dateDepart = dateDepart;
    }
    public Long getPlacesDispo() {
        return this.placesDispo;
    }
    
    public void setPlacesDispo(Long placesDispo) {
        this.placesDispo = placesDispo;
    }
    public BigDecimal getDuree() {
        return this.duree;
    }
    
    public void setDuree(BigDecimal duree) {
        this.duree = duree;
    }
    public Long getPrix() {
        return this.prix;
    }
    
    public void setPrix(Long prix) {
        this.prix = prix;
    }
    public Set getEtapes() {
        return this.etapes;
    }
    
    public void setEtapes(Set etapes) {
        this.etapes = etapes;
    }
    public Set getReservations() {
        return this.reservations;
    }
    
    public void setReservations(Set reservations) {
        this.reservations = reservations;
    }




}


