package beans;
// Generated 12 juil. 2016 14:22:32 by Hibernate Tools 4.3.1


import java.util.Date;

/**
 * Etape generated by hbm2java
 */
public class Etape  implements java.io.Serializable {


     private long ordre;
     private Circuit circuit;
     private String nomLieu;
     private String ville;
     private String pays;
     private Date dateEtape;
     private Long duree;

    public Etape() {
    }

	
    public Etape(long ordre) {
        this.ordre = ordre;
    }
    public Etape(long ordre, Circuit circuit, String nomLieu, String ville, String pays, Date dateEtape, Long duree) {
       this.ordre = ordre;
       this.circuit = circuit;
       this.nomLieu = nomLieu;
       this.ville = ville;
       this.pays = pays;
       this.dateEtape = dateEtape;
       this.duree = duree;
    }
   
    public long getOrdre() {
        return this.ordre;
    }
    
    public void setOrdre(long ordre) {
        this.ordre = ordre;
    }
    public Circuit getCircuit() {
        return this.circuit;
    }
    
    public void setCircuit(Circuit circuit) {
        this.circuit = circuit;
    }
    public String getNomLieu() {
        return this.nomLieu;
    }
    
    public void setNomLieu(String nomLieu) {
        this.nomLieu = nomLieu;
    }
    public String getVille() {
        return this.ville;
    }
    
    public void setVille(String ville) {
        this.ville = ville;
    }
    public String getPays() {
        return this.pays;
    }
    
    public void setPays(String pays) {
        this.pays = pays;
    }
    public Date getDateEtape() {
        return this.dateEtape;
    }
    
    public void setDateEtape(Date dateEtape) {
        this.dateEtape = dateEtape;
    }
    public Long getDuree() {
        return this.duree;
    }
    
    public void setDuree(Long duree) {
        this.duree = duree;
    }




}


